# Generated by Django 3.2.12 on 2023-07-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews_and_ratings',
            options={'verbose_name_plural': 'reviews_and_ratings'},
        ),
    ]
