# Generated by Django 3.2.12 on 2023-07-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_vendor'),
        ('cart', '0003_product_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cart',
            name='products',
            field=models.ManyToManyField(to='inventory.Product'),
        ),
    ]
