# Generated by Django 3.2.12 on 2023-08-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_image'),
        ('cart', '0009_alter_product_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cart',
            name='products',
            field=models.ManyToManyField(to='inventory.Product'),
        ),
    ]
